### PR TITLE
Upgrade to spring-boot 1.4.0

### PR DESCRIPTION
**Pull request by VolkerK**
Spring Boot 1.3.x won't work with spring-rabbit-1.6.0

`java.lang.NoSuchMethodError: org.springframework.amqp.core.MessageProperties.getCorrelationIdString()Ljava/lang/String;
at org.springframework.amqp.rabbit.support.DefaultMessagePropertiesConverter.fromMessageProperties(DefaultMessagePropertiesConverter.java:183) ~[spring-rabbit-1.6.0.RELEASE.jar!/:na]`

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@VolkerK Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-amqp-samples&pullRequestId=15)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-amqp-samples&pullRequestId=15) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/faq) for frequently asked questions.

**Comment by artembilan** [comment]
Merged as https://github.com/spring-projects/spring-amqp-samples/commit/8aad43786f7bc138c185ecf57cc474e1de73fb2b

Thank you for contribution.
Looking forward for more!
